### PR TITLE
Remove wrapping of SQLException

### LINKED ISSUE #56: Follow subscriptions no longer work after "Connection to [url] refused".
PGDriverManagerConnectionSupplier.get() catches every SQLException, wraps it inside a RuntimeExpcetion and throws that exception. PGListener (the caller) catches only SQLExceptions in its internal listenerThread. If any other Exception occurs the thread finishes without any more information and the FactCast no longer listens for postgres notifications. 
As a result of that any old or new follow subscription will not receive any new events after its initial catchup.

The corresponding stacktrace looks like the following (line numbers may wary slightly)
```
java.lang.RuntimeException: Cannot acquire Connection from DriverManager: jdbc:postgresql://factcast-test.c2nhv0ptpb7v.eu-central-1.rds.amazonaws.com:5432/TestDB
	at org.factcast.store.pgsql.internal.listen.PGDriverManagerConnectionSupplier.get(PGDriverManagerConnectionSupplier.java:49)
	at org.factcast.store.pgsql.internal.listen.PGDriverManagerConnectionSupplier.get(PGDriverManagerConnectionSupplier.java:21)
	at org.factcast.store.pgsql.internal.listen.PGListener.lambda$listen$0(PGListener.java:64)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: Connection to factcast-test.c2nhv0ptpb7v.eu-central-1.rds.amazonaws.com:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:265)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at org.factcast.store.pgsql.internal.listen.PGDriverManagerConnectionSupplier.get(PGDriverManagerConnectionSupplier.java:44)
	... 3 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:68)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
	... 8 more
```

### PR DESCRIPTION
**Pull request by luk2302**
this fixes #56 (second try)

### CODE REVIEW

File: factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/listen/PgConnectionSupplier.java [hunk 1]
```diff
@@ -18,15 +17,16 @@
 import lombok.RequiredArgsConstructor;
 import lombok.extern.slf4j.Slf4j;
 
+@Slf4j
 @Component
 @RequiredArgsConstructor
-@Slf4j
-public class PGDriverManagerConnectionSupplier implements Supplier<PgConnection> {
```
Comment (uweschaefer) [inline factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/listen/PgConnectionSupplier.java]: Hi Lukas, thanks for contributing.
What is the reason for this change?

Comment (uweschaefer) [reply factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/listen/PgConnectionSupplier.java]: sorry, i poorly expressed myself. i was referring to the removal of implements Supplier<PgConnection>

Comment (luk2302) [reply factcast-store-pgsql/src/main/java/org/factcast/store/pgsql/internal/listen/PgConnectionSupplier.java]: Then the reason is that otherwise we cannot declare the `PgConnectionSupplier.get` method to throw a checked `SQLException`. The alternative would be to make the get method throw a custom `RuntimeException` which the caller would have to explicitly know about to not run into the same problem again in the future. Or have the caller catch all `RuntimeException`s in general which I do not like either. Since two other methods called from within the `listenerThread` already can cause `SQLException`s and exceptions from this `get` method should be handled in the same way I prefer dropping the `Supplier<...>`.
